# configuration file for production environment

# Logs
log: "core"

logger: "file"
log_file: "error_log"
log_path: ""

warnings: 1 
traces: 1
show_errors: 1 

# cache route resolution for maximum performance
route_cache: 1

# Plugins
plugins:
  DBIC:
    default:
      schema_class: DB::Schema
      options:
        mysql_enable_utf8: 1

